spring:
  application:
    name: webdiet-api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

server:
  port: 8200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    path: ./logs
